# Generated by Django 4.0.1 on 2022-01-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Прізвище'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greeting',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
    ]
