# Generated by Django 4.0.1 on 2022-01-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_greeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время приветствия'),
        ),
    ]
